---
roles:
  # - src: https://github.com/stuttgart-things/deploy-configure-rke.git
  #   scm: git
  #   version: main
  - src: https://github.com/stuttgart-things/configure-rke-node.git
    scm: git
    version: main
  - src: https://github.com/stuttgart-things/install-requirements.git
    scm: git
    version: 2026.09.17
  - src: https://github.com/stuttgart-things/download-install-binary.git
    scm: git
    version: 2026.10.01
  - src: https://github.com/stuttgart-things/create-os-user.git
    scm: git
    version: 2026.07.22
  - src: https://github.com/stuttgart-things/install-configure-docker.git
    scm: git
    version: 2026.07.19
