---
- name: Download and install addons
  ansible.builtin.include_tasks: install-addons.yaml

- name: Create rancher cluster folder 
  ansible.builtin.file:
    path: "{{ rancher_cluster_folder }}"
    state: directory
    mode: '0755'
  tags: setup
  when: inventory_hostname in groups['initial_master_node']
  
- name: Create rancher cluster config
  ansible.builtin.template:
    src: rke1-config.yaml.j2
    dest: "{{ rancher_cluster_folder }}/{{ rke_cluster_config_name }}"
    backup: yes
    mode: u=rw,g=,o=
  tags: config
  when: inventory_hostname in groups['initial_master_node']

- name: Download and install rke1-installer
  ansible.builtin.include_role:
    name: download-install-binary
  loop: "{{ lookup('dict', rke_installer_binary, wantlist=True) }}"
  when: install_rke_installer|bool and inventory_hostname in groups['initial_master_node']

- name: Check if rancher key-pair does already exist 
  ansible.builtin.stat:
    path: "{{ path_to_private_key }}"
  register: keypair_exists 
  tags: keysetup
  when: inventory_hostname in groups['initial_master_node']

- name: Generate rancher key-pair for creating/managing a rancher ha-server
  community.crypto.openssh_keypair:
    path: "{{ path_to_private_key }}"
    type: rsa
    size: 2048
    force: no
    unsafe_writes: no
  when: inventory_hostname in groups['initial_master_node']
  tags: keysetup

- name: Read pub key 
  block:
    
    - name: Read pub key from inital master
      ansible.builtin.shell: cat {{ path_to_private_key }}.pub
      register: pub_key

    - name: Set pub key from inital master
      ansible.builtin.set_fact:
        rke_pub_key: "{{ pub_key.stdout }}"
      run_once: true

  when: inventory_hostname in groups['initial_master_node']

- name: Create rke user
  ansible.builtin.include_role:
    name: create-os-user
  vars:
    users: "{{ rke_user }}"

- name: Provision rke
  ansible.builtin.shell: |
    yes | {{ path_to_rke_installer_binary }} {{ rke_parameter }} --config ./{{ rke_cluster_config_name }}
  args:
    chdir: "{{ rancher_cluster_folder }}"
  register: rke_setup
  ignore_errors: true
  when: inventory_hostname in groups['initial_master_node']

- name: Retry Provisioning of rke
  ansible.builtin.shell: |
    yes | {{ path_to_rke_installer_binary }} remove --config ./{{ rke_cluster_config_name }}
    yes | {{ path_to_rke_installer_binary }} up --config ./{{ rke_cluster_config_name }}
  args:
    chdir: "{{ rancher_cluster_folder }}"
  register: rke_setup
  when: inventory_hostname in groups['initial_master_node'] and rke_setup.rc != 0
