---
- name: Install kubectl
  block:
    - ansible.builtin.set_fact: bin="{{ kubectl_binary|combine(kubectl_binary) }}"
    - ansible.builtin.include_role:
        name: download-install-binary
  when: install_kubectl|bool

- name: Install helm
  block:
    - ansible.builtin.set_fact: bin="{{ helm_binary|combine(helm_binary) }}"
    - ansible.builtin.include_role:
        name: download-install-binary
  when: install_helm|bool
