---
- name: Check for existing of cluster-config and cluster state files
  ansible.builtin.stat:
    path: "{{ item }}"
  loop: 
    - "{{ path_to_rke_statefile }}"
    - "{{ path_to_rke_cluster_config }}"
    - "{{ path_to_kubeconfig }}"
    - "{{ path_tls_crt }}"
    - "{{ path_tls_key }}"
    - "{{ path_cacerts_pem }}"

- name: Check for desired upgrade version in rke installer
  ansible.builtin.shell: |
    {{ path_to_rke_installer_binary }} config --list-version --all | grep '{{ rke_upgrade_version }}'
  register: rke_installer_available_versions

- name: Check for version in cluster-config file 
  ansible.builtin.shell: |
    cat {{ rancher_cluster_folder }}/{{ rke_cluster_config_name }} | awk '/kubernetes_version:/ {print $2}'
  register: rke_version_cluster_config

- name: Check for installed k8s version on rancher-ha-server 
  ansible.builtin.shell: |
    {{ path_to_kubectl_binary }} --kubeconfig={{ path_to_kubeconfig }} version --short | grep 'Server' | awk '{print $3}'
  register: k8s_version_installed

- ansible.builtin.debug:
    msg: "rancher-ha-server is installed w/ {{ k8s_version_installed.stdout }}-rancher1-1. The upgrade will install: {{ rke_upgrade_version }}"

- name: Add the desired rke version to cluster config
  ansible.builtin.lineinfile:
    dest: "{{ rancher_cluster_folder }}/{{ rke_cluster_config_name }}"
    regexp: '^(.*)kubernetes_version: (.*)$'
    line: 'kubernetes_version: {{ rke_upgrade_version }}'

- name: Upgrade rke
  ansible.builtin.shell: |
    {{ path_to_rke_installer_binary }} {{ rke_parameter }} --config ./{{ rke_cluster_config_name }}
  args:
    chdir: "{{ rancher_cluster_folder }}"
  when: rke_upgrade_version.split("-")[0] != k8s_version_installed.stdout.split("-")[0]

- name: Check for installed k8s version on rancher-ha-server after upgrade process 
  ansible.builtin.shell: |
    {{ path_to_kubectl_binary }} --kubeconfig={{ path_to_kubeconfig }} version --short | grep 'Server' | awk '{print $3}'
  register: k8s_version_upgraded

- name: Output post upgrade message
  ansible.builtin.debug:
    msg: "rancher-ha-server was successfully upgraded to: {{ rke_upgrade_version }} (kubernetes: {{ k8s_version_upgraded.stdout }})"
