---
#singlecluster
initial_master_node:
  hosts:
    10.100.136.130
additional_master_nodes:
  hosts:
    10.100.136.91:
    10.100.136.92:

#multicluster
# initial_master_node:
#   hosts:
#     rke2-test-molecule.labul.sva.de
# additional_master_nodes:
#   hosts:
#     rke2-test-molecule-2.labul.sva.de:
#     rke2-test-molecule-3.labul.sva.de:
