---
dependency:
  name: galaxy
  options:
    ignore-errors: false
    force: true
    role-file: requirements.yml
    requirements-file: collections.yml

role_name_check: 1
driver:
  name: default
  managed: False
platforms:
  - name: cluster-test1.labul.sva.de
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 3
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-k3s.yaml} #converge.yml
  inventory:
    links:
      hosts: inventory.yaml

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - prepare
    - converge
