---
dependency:
  name: galaxy
  options:
    ignore-errors: false
    force: true
    role-file: requirements.yml
    requirements-file: collections.yml

role_name_check: 1
driver:
  name: default
  managed: False
platforms:
  - name: rke2-test-molecule.labul.sva.de
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 3
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    links:
      hosts: inventory.yaml

scenario:
  name: default
  test_sequence:
    # - destroy
    - dependency
    - syntax
    # - create
    - prepare
    - converge

    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
