---
dependency:
  name: galaxy
  options:
    ignore-errors: false
    force: true
    role-file: requirements.yml
    requirements-file: collections.yml

role_name_check: 1
driver:
  name: default
  managed: False
platforms:
  - name: 10.31.103.33
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 1
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-rke2.yaml} #converge.yml
  inventory:
    links:
      hosts: inventory.yaml

scenario:
  name: rke2
  test_sequence:
    - dependency
    - syntax
    - prepare
    - converge
