---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    rke_state: absent #present #absent #present  #present #absent
    rke_version: 2
    rke2_k8s_version: 1.33.4
    rke2_airgapped_installation: true
    rke2_release_kind: rke2r1 # rke2r2
    cluster_setup: multinode
    disable_rke2_components:
      - rke2-ingress-nginx
      - rke-snapshot-controller
      - rke2-kube-proxy
    rke2_cni: none
    install_cilium: true

  roles:
    - role: deploy-configure-rke
