---
name: Build Ansible Collection
on:
  push:
    branches:
      - main
    paths:
      - collection.yaml

jobs:
  Build-Collection:
    name: Build Ansible Collection
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-ansible-collection.yaml@main    
    with:
      runs-on: ghr-deploy-configure-rke-labda-test
      environment-name: k8s
      continue-error: false
      collection-file: collection.yaml
